export const W = {
  bg: 'var(--w-bg)',
  canvas: 'var(--w-canvas)',
  panel: 'var(--w-panel)',
  surface: 'var(--w-surface)',
  surfaceHigh: 'var(--w-surface-high)',
  card: 'var(--w-card)',
  cardHover: 'var(--w-card-hover)',
  inset: 'var(--w-inset)',
  border: 'var(--w-border)',
  border2: 'var(--w-border2)',
  border3: 'var(--w-border3)',
  text1: 'var(--w-text1)',
  text2: 'var(--w-text2)',
  text3: 'var(--w-text3)',
  text4: 'var(--w-text4)',
  icon: 'var(--w-icon)',
  iconMuted: 'var(--w-icon-muted)',
  violet: 'var(--w-violet)',
  violetSoft: 'var(--w-violet-soft)',
  violetGlow: 'var(--w-violet-glow)',
  violetSubtle: 'var(--w-violet-subtle)',
  cyan: 'var(--w-cyan)',
  cyanGlow: 'var(--w-cyan-glow)',
  cyanSubtle: 'var(--w-cyan-subtle)',
  blue: '#3B82F6',
  blueGlow: 'rgba(59, 130, 246, 0.16)',
  blueSubtle: 'rgba(59, 130, 246, 0.08)',
  blueMuted: '#4F83F1',
  blueDark: '#1D4ED8',
  teal: '#00A89E',
  tealMuted: '#007C75',
  tealDark: '#005E59',
  green: '#16A366',
  greenGlow: 'rgba(22, 163, 102, 0.16)',
  greenSubtle: 'rgba(22, 163, 102, 0.08)',
  amber: '#D4890A',
  amberGlow: 'rgba(212, 137, 10, 0.18)',
  amberSubtle: 'rgba(212, 137, 10, 0.08)',
  red: '#DC3545',
  redGlow: 'rgba(220, 53, 69, 0.16)',
  redSubtle: 'rgba(220, 53, 69, 0.08)',
  glass: 'var(--w-glass)',
  glass02: 'var(--w-glass-02)',
  glass03: 'var(--w-glass-03)',
  glass04: 'var(--w-glass-04)',
  glass05: 'var(--w-glass-05)',
  glass06: 'var(--w-glass-06)',
  glass07: 'var(--w-glass-07)',
  glass08: 'var(--w-glass-08)',
  glass12: 'var(--w-glass-12)',
  glassHover: 'var(--w-glass-hover)',
  overlay88: 'var(--w-overlay-88)',
  shadowSm: 'var(--w-shadow-sm)',
  shadowMd: 'var(--w-shadow-md)',
  shadowLg: 'var(--w-shadow-lg)',
  appShellGridLine: 'var(--w-app-shell-grid)',
  mapHudPanelBg: 'var(--w-map-hud-panel)',
  mapHudPanelBgWQ: 'var(--w-map-hud-wq)',
  mapHudPanelBgWQWarn: 'var(--w-map-hud-wq-warn)',
  mapHudBorderCyan: 'var(--w-map-hud-border-cyan)',
  mapHudBorderCyanStrong: 'var(--w-map-hud-border-cyan-strong)',
  mapHudBorderAmber: 'var(--w-map-hud-border-amber)',
  mapHudBorderRed: 'var(--w-map-hud-border-red)',
  mapControlBg: 'var(--w-map-control-bg)',
  mapControlBorder: 'var(--w-map-control-border)',
  chromeHeaderBg: 'var(--w-chrome-header-bg)',
  scrim: 'var(--w-scrim)',
  navScrim: 'var(--w-chrome-header-bg)',
  hairlineBorder: 'var(--w-border-hairline)',
  chromeBorder: 'var(--w-border-chrome)',
  bannerBgMock: 'var(--w-banner-bg-mock)',
  bannerBgLive: 'var(--w-banner-bg-live)',
  bannerEdgeMock: 'var(--w-banner-edge-mock)',
  bannerEdgeLive: 'var(--w-banner-edge-live)',
  mapWaterFill: 'var(--w-map-water-fill)',
  mapHalo: 'var(--w-map-halo)',
  mapCommercial: 'var(--w-map-commercial)',
  mapSecondary: 'var(--w-map-secondary)',
  textInverse: 'var(--w-text-inverse)',
  redBorderSoft: 'var(--w-red-border-soft)',
  redBadgeBg: 'var(--w-red-badge-bg)',
  gray: '#6B7280',
  graySubtle: 'rgba(107, 114, 128, 0.08)',
  radius: { xs: 4, sm: 7, md: 10, lg: 14 },
} as const

export const V = W.violet
